services:
  # 1. 백엔드(FastAPI) 서비스 정의
  backend:
    build:
      context: ./suvisdev      # suvisdev 폴더 안에 있는 Dockerfile을 읽어라
      dockerfile: Dockerfile
    ports:
      - "8000:8000"            # 내 진짜 컴퓨터의 8000번 포트와 도커의 8000번 포트를 연결해라
    environment:
      - ENV=production
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
