"""TMDB 키워드(영어) → 한국어 태그 라벨 매핑.

키워드 태그 백필(`scripts/backfill_tmdb_keyword_tags.py`)이 쓴다. 채팅 태그
매칭이 `tags.label ILIKE %한국어키워드%`라서, 사전에 없는 TMDB 키워드는 태그로
만들어도 검색에 안 걸린다 — 실제 채팅 질의 주제(교사 데이터셋 스킵 49건 실측
포함)에 대응하는 것만 선별해 둔다. 여러 영어 키워드가 같은 라벨로 합쳐질 수
있다(예: heist/robbery → 강도).
"""

from __future__ import annotations

TMDB_KEYWORD_TO_LABEL: dict[str, str] = {
    # 크리처·호러
    "zombie": "좀비",
    "zombie apocalypse": "좀비",
    "vampire": "뱀파이어",
    "ghost": "유령",
    "haunted house": "유령",
    "exorcism": "오컬트",
    "occult": "오컬트",
    "possession": "오컬트",
    "monster": "괴물",
    "shark": "상어",
    "dinosaur": "공룡",
    "serial killer": "연쇄살인마",
    "slasher": "슬래셔",
    # SF·세계관
    "superhero": "슈퍼히어로",
    "time travel": "시간여행",
    "time loop": "타임루프",
    "space": "우주",
    "space travel": "우주",
    "astronaut": "우주",
    "alien": "외계인",
    "alien invasion": "외계인",
    "robot": "로봇",
    "artificial intelligence (a.i.)": "인공지능",
    "artificial intelligence": "인공지능",
    "cyborg": "로봇",
    "dystopia": "디스토피아",
    "post-apocalyptic future": "포스트아포칼립스",
    "apocalypse": "포스트아포칼립스",
    "parallel world": "멀티버스",
    "alternate reality": "멀티버스",
    "multiverse": "멀티버스",
    "virtual reality": "가상현실",
    "dream": "꿈",
    "amnesia": "기억상실",
    "clone": "복제인간",
    # 범죄·스릴러
    "heist": "강도",
    "robbery": "강도",
    "bank robbery": "은행강도",
    "bank heist": "은행강도",
    "con artist": "사기꾼",
    "con man": "사기꾼",
    "revenge": "복수",
    "kidnapping": "납치",
    "hostage": "인질",
    "gangster": "조폭",
    "organized crime": "조폭",
    "mafia": "마피아",
    "drug cartel": "마약",
    "drug trafficking": "마약",
    "drug dealer": "마약",
    "prison": "감옥",
    "prison escape": "탈옥",
    "escape room": "밀실",
    "spy": "첩보",
    "espionage": "첩보",
    "secret agent": "첩보",
    "assassin": "암살자",
    "hitman": "암살자",
    "detective": "형사",
    "police": "형사",
    "police detective": "형사",
    "undercover": "잠입수사",
    "neo-noir": "느와르",
    "film noir": "느와르",
    "psychological thriller": "심리스릴러",
    "conspiracy": "음모",
    # 직업·무대
    "courtroom": "법정",
    "courtroom drama": "법정",
    "lawyer": "변호사",
    "trial": "법정",
    "hospital": "병원",
    "doctor": "의사",
    "surgeon": "의사",
    "journalist": "기자",
    "journalism": "언론",
    "newspaper": "언론",
    "politics": "정치",
    "politician": "정치",
    "election": "정치",
    "president": "정치",
    "chef": "요리",
    "cooking": "요리",
    "restaurant": "요리",
    "food": "요리",
    "teacher": "교사",
    "firefighter": "소방관",
    # 음악·예술
    "jazz": "재즈",
    "musical": "뮤지컬",
    "music": "음악",
    "musician": "음악",
    "singer": "음악",
    "rock band": "밴드",
    "band": "밴드",
    "dance": "춤",
    "dancing": "춤",
    "ballet": "발레",
    "painter": "화가",
    "artist": "예술가",
    "writer": "작가",
    "novelist": "작가",
    "mathematician": "수학자",
    "genius": "천재",
    "piano": "피아노",
    # 스포츠
    "baseball": "야구",
    "soccer": "축구",
    "football": "축구",
    "basketball": "농구",
    "boxing": "복싱",
    "boxer": "복싱",
    "marathon": "마라톤",
    "olympics": "올림픽",
    "sports": "스포츠",
    # 장소·상황
    # 도시·지역(2026-09-03 평가셋 실측 — "뉴욕 배경"·"유럽 배경 로맨스" 무관 픽):
    # 채팅 질의가 도시 단위보다 "유럽" 같은 권역 표현이라 유럽 도시는 권역
    # 라벨로 합친다. 뉴욕은 질의에 그대로 등장해 도시 라벨 유지.
    "new york city": "뉴욕",
    "manhattan": "뉴욕",
    "brooklyn, new york city": "뉴욕",
    "paris, france": "유럽",
    "london, england": "유럽",
    "rome, italy": "유럽",
    "berlin, germany": "유럽",
    "venice, italy": "유럽",
    "office": "직장",
    "workplace": "직장",
    "political thriller": "정치",
    "sea": "바다",
    "ocean": "바다",
    "island": "섬",
    "mountain": "산",
    "mountaineering": "등반",
    "climbing": "등반",
    "airplane": "비행기",
    "aviation": "비행기",
    "pilot": "비행기",
    "submarine": "잠수함",
    "train": "기차",
    "road trip": "로드트립",
    "travel": "여행",
    "desert": "사막",
    "jungle": "정글",
    "survival": "생존",
    "stranded": "생존",
    "disaster": "재난",
    "natural disaster": "재난",
    "earthquake": "재난",
    "tsunami": "재난",
    "pandemic": "전염병",
    "virus": "전염병",
    "epidemic": "전염병",
    # 전쟁·역사
    "war": "전쟁",
    "world war ii": "전쟁",
    "world war i": "전쟁",
    "soldier": "전쟁",
    "korean war": "한국전쟁",
    "japanese occupation of korea": "일제강점기",
    "joseon dynasty": "조선시대",
    "historical": "역사",
    "based on true story": "실화",
    "based on a true story": "실화",
    "biography": "실화",
    # 관계·정서
    "friendship": "우정",
    "first love": "첫사랑",
    "breakup": "이별",
    "coming of age": "성장",
    "youth": "청춘",
    "family": "가족",
    "father son relationship": "부자관계",
    "mother daughter relationship": "모녀관계",
    "wedding": "결혼",
    "christmas": "크리스마스",
    "dog": "강아지",
    "cat": "고양이",
    "animal": "동물",
    # 액션
    "martial arts": "무술",
    "car chase": "카체이스",
    "car race": "레이싱",
    "sword fight": "검술",
}
